version: "3.9"

services:
  db_tranz:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - net

  app:
    build:
      dockerfile: ./Dockerfile
    command: ["docker/app.sh"]
    expose:
      - 8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db_tranz
      - rabbitmq
    networks:
      - net

  consumer:
    build: ./consumer
    container_name: consumer
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db_tranz
    networks:
      - net

  nginx_lib:
    container_name: tranz-nginx
    build: ./nginx
    volumes:
      - log_nginx:/var/log/nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - app
    networks:
      - net

volumes:
  postgres_volume:
  log_nginx:
  rabbitmq-data:

networks:
  net:
    driver: bridge