"""add in table scores account_number

Revision ID: 817f7786f396
Revises: 96726a03bcb0
Create Date: 2025-02-10 19:44:44.064473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "817f7786f396"
down_revision: Union[str, None] = "96726a03bcb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores", sa.Column("account_number", sa.String(length=20), nullable=False)
    )
    op.alter_column(
        "scores",
        "balance",
        existing_type=sa.INTEGER(),
        type_=sa.NUMERIC(precision=15, scale=2),
        existing_nullable=False,
    )
    op.create_index(
        "idx_account_number_hash",
        "scores",
        ["account_number"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_unique_constraint(None, "scores", ["account_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scores", type_="unique")
    op.drop_index("idx_account_number_hash", table_name="scores", postgresql_using="hash")
    op.alter_column(
        "scores",
        "balance",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("scores", "account_number")
    # ### end Alembic commands ###
