"""change format amount in table payments

Revision ID: ed4699c5bbb3
Revises: 817f7786f396
Create Date: 2025-02-15 09:09:26.101926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed4699c5bbb3"
down_revision: Union[str, None] = "817f7786f396"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.INTEGER(),
        type_=sa.NUMERIC(precision=15, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
